version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: element_web_1
      APP_PORT: 80

  web:
    image: vectorim/element-web:v1.11.45@sha256:bfbe1745c57a19579bb4bf1e8760c1f11413cd6d75b036e80787671e1911f838    
    # NGINX parent container requires root
    # user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
