name: Test Files

on:
  pull_request:
    paths:
      - '**/docker-compose.yml'
      - '**/umbrel-app.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E 'docker-compose.yml|umbrel-app.yml')"
      shell: bash

    - name: Run docker-compose checks
      run: |
        IFS=$'\n' read -d '' -r -a files <<< "${{ steps.getfile.outputs.files }}"
        for file in "${files[@]}"
        do
          if [[ $file == *docker-compose.yml ]]
          then
            chmod +x ./docker-compose-checks.sh
            ./docker-compose-checks.sh "$file"
          fi
        done
      shell: bash

    - name: Run umbrel app checks
      run: |
        IFS=$'\n' read -d '' -r -a files <<< "${{ steps.getfile.outputs.files }}"
        for file in "${files[@]}"
        do
          if [[ $file == *umbrel-app.yml ]]
          then
            chmod +x ./umbrel-app-checks.sh
            ./docker-compose-checks.sh "$file"
          fi
        done
      shell: bash